services:
  postgres:
    image: postgres:16
    container_name: resource-serv
    restart: always

    environment:
      POSTGRES_DB: resource
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
    volumes:
      - resource_postgres_data:/var/lib/postgresql/data

volumes:
  resource_postgres_data: